spring:
  application:
    name: BookingHotelApp

  datasource:
    url: jdbc:postgresql://localhost:5433/hotels_db
    username: postgres
    password: postgres


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: false

  messages:
    fallback-to-system-locale: false
  web:
    locale: en

  kafka:
    bootstrap-servers: localhost:9092

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/statisticsdatabase?authSource=admin

app:
  kafka:
    userTopic: "user-events"
    bookingTopic: "booking-events"
    groupId: "group-id"

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only



